# Generated by Django 5.1.7 on 2025-04-02 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام طرح')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price_per_day', models.BigIntegerField(verbose_name='قیمت روزانه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگانه؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('subscription_status', models.CharField(choices=[('default', 'پیش\u200cفرض'), ('special', 'خاص')], default='default', max_length=30, verbose_name='وضعیت اشتراک')),
                ('duration', models.IntegerField(default=1, verbose_name='مدت زمان (روز)')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین پرداخت')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='پرداخت بعدی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='Subscriptions.subscriptionplan', verbose_name='طرح اشتراک')),
            ],
            options={
                'verbose_name': 'اشتراک آکهی',
                'verbose_name_plural': 'اشتراک های آگهی',
            },
        ),
    ]
