# Generated by Django 5.1.7 on 2025-04-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementsubscription',
            name='payment_status',
        ),
    ]
