# Generated by Django 5.1.7 on 2025-04-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_remove_advertisementsubscription_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementsubscription',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='advertisementsubscription',
            name='next_payment_date',
        ),
    ]
