# Generated by Django 5.1.7 on 2025-04-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0003_remove_advertisementsubscription_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementsubscription',
            name='subscription_status',
            field=models.CharField(choices=[('default', 'پیش\u200c فرض'), ('special', 'خاص')], default='default', max_length=30, verbose_name='وضعیت اشتراک'),
        ),
    ]
