# Generated by Django 5.1.7 on 2025-06-03 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industry', '0003_industry_category'),
        ('Resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerresume',
            name='job_seeker_profile',
        ),
        migrations.AddField(
            model_name='jobseekerresume',
            name='job_seeker',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='جوینده کار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_industry', to='Industry.industry', verbose_name='صنعت'),
        ),
    ]
