# Generated by Django 5.1.7 on 2025-06-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industry', '0003_industry_category'),
        ('Locations', '0002_remove_city_slug_remove_province_slug'),
        ('Resumes', '0002_remove_jobseekerresume_job_seeker_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_locations', to='Locations.city', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='availability',
            field=models.CharField(choices=[('immediately', 'فوری'), ('with_notice', 'با اطلاع'), ('not_available', 'غیرقابل دسترسی')], default='immediately', max_length=20, null=True, verbose_name='وضعیت دسترسی'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='cv',
            field=models.FileField(null=True, upload_to='jobseekers/resumes/', verbose_name='رزومه'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='degree',
            field=models.CharField(choices=[('Below Diploma', 'زیر دیپلم'), ('Diploma', 'دیپلم'), ('Associate', 'فوق دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('Doctorate', 'دکترا')], max_length=20, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='expected_salary',
            field=models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=20, null=True, verbose_name='حقوق مورد نظر'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='experience',
            field=models.CharField(choices=[('No EXPERIENCE', 'بدون سابقه کار'), ('Less than Three', 'کمتر از 3 سال'), ('Three or More', '3 تا 6 سال'), ('Six or More', 'بیشتر از 6 سال')], max_length=50, null=True, verbose_name='سابقه کاری'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='gender',
            field=models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=20, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='headline',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_industry', to='Industry.industry', verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='لینکدین'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='preferred_job_type',
            field=models.CharField(choices=[('Full-Time', 'تمام وقت'), ('Part-Time', 'پاره وقت'), ('Remote', 'دورکاری'), ('Internship', 'کارآموزی')], max_length=20, null=True, verbose_name='نوع شغل مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='soldier_status',
            field=models.CharField(choices=[('Completed', 'پایان خدمت'), ('Permanent Exemption', 'معافیت دائم'), ('Educational Exemption', 'معافیت تحصیلی'), ('Not Completed', 'نااتمام')], max_length=30, null=True, verbose_name='وضعیت سربازی'),
        ),
        migrations.AlterField(
            model_name='jobseekerresume',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='jobseekerskill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Job_Seeker', to='Industry.skill', verbose_name='مهارت'),
        ),
    ]
