# Generated by Django 5.1.7 on 2025-04-02 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advertisements', '0001_initial'),
        ('Profiles', '0005_remove_experience_job_seeker_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام دسته\u200cبندی گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات دسته\u200cبندی')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('reported_jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_reports_against', to='Profiles.jobseekerprofile', verbose_name='جوینده کار گزارش شده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportcategory', verbose_name='دسته\u200cبندی گزارش')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('reported_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reports_against', to='Profiles.employerprofile', verbose_name='کارفرمای گزارش شده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200c دهنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportcategory', verbose_name='دسته\u200cبندی گزارش')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against_joqb_advertisement', to='Advertisements.advertisement', verbose_name='آگهی گزارش شده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportcategory', verbose_name='دسته\u200cبندی گزارش')),
            ],
        ),
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('reported_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reports_against', to='Profiles.adminprofile', verbose_name='مدیر گزارش شده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportcategory', verbose_name='دسته\u200cبندی گزارش')),
            ],
        ),
        migrations.CreateModel(
            name='SupportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'در انتظار'), ('R', 'حل شده'), ('RJ', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportcategory', verbose_name='دسته\u200cبندی گزارش')),
                ('reported_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_reports_against', to='Profiles.supportprofile', verbose_name='پشتیبان گزارش شده')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
        ),
    ]
