# Generated by Django 5.1.7 on 2025-04-06 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportreport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supportreport',
            name='reported_support',
        ),
        migrations.RemoveField(
            model_name='supportreport',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='AdminReport',
        ),
        migrations.DeleteModel(
            name='SupportReport',
        ),
    ]
