# Generated by Django 5.1.7 on 2025-06-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0004_remove_jobadvertisement_subscription_and_more'),
        ('Reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerreport',
            name='reported_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reports', to=settings.AUTH_USER_MODEL, verbose_name='کارفرمای گزارش شده'),
        ),
        migrations.AlterField(
            model_name='employerreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_employer_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200c دهنده'),
        ),
        migrations.AlterField(
            model_name='jobseekerreport',
            name='reported_jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_reports', to=settings.AUTH_USER_MODEL, verbose_name='جوینده کار گزارش شده'),
        ),
        migrations.AlterField(
            model_name='jobseekerreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_jobseeker_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده'),
        ),
        migrations.CreateModel(
            name='AdvertisementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'در انتظار'), ('RE', 'حل شده'), ('RJ', 'رد شده')], default='PE', max_length=2, verbose_name='وضعیت گزارش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_reports', to='Advertisements.advertisement', verbose_name='آگهی گزارش شده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.reportcategory', verbose_name='دسته\u200cبندی گزارش')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_advertisements_reports', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
        ),
    ]
