# Generated by Django 5.1.7 on 2025-03-31 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0004_jobseekerresumeadvertisement'),
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumereport',
            name='resume',
        ),
        migrations.AddField(
            model_name='resumereport',
            name='resume_advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against_resume_advertisement', to='Advertisements.jobseekerresumeadvertisement', verbose_name='رزومه گزارش شده'),
            preserve_default=False,
        ),
    ]
