# Generated by Django 5.1.7 on 2025-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
