# Generated by Django 5.1.7 on 2025-05-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='company_name',
        ),
    ]
