# Generated by Django 5.2.1 on 2025-06-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_email_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_card_info',
        ),
        migrations.DeleteModel(
            name='IdCardInFormation',
        ),
    ]
