# Generated by Django 5.1.7 on 2025-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXP', 'منقضی شده'), ('ACT', 'فعال')], default='ACT', max_length=3, verbose_name='وضعیت')),
                ('Phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('token', models.CharField(max_length=250, unique=True, verbose_name='توکن')),
                ('code', models.CharField(max_length=6, verbose_name='کد OTP')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': 'رمزهای یکبار مصرف',
            },
        ),
    ]
