# Generated by Django 5.1.7 on 2025-03-22 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXP', 'منقضی شده'), ('ACT', 'فعال')], default='ACT', max_length=3, verbose_name='وضعیت')),
                ('token', models.CharField(max_length=250, unique=True, verbose_name='توکن')),
                ('code', models.CharField(max_length=6, verbose_name='کد OTP')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': 'رمزهای یکبار مصرف',
            },
        ),
        migrations.CreateModel(
            name='UserRegisterOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('password', models.CharField(max_length=128, verbose_name='هش رمز عبور')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('password_conf', models.CharField(max_length=255, verbose_name='تکرار رمزعبور')),
                ('user_type', models.CharField(default='JS', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_otps', to='Authentication.onetimepassword', verbose_name='ارجاع رمز یکبار مصرف')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف ثبت نام کاربر',
                'verbose_name_plural': 'رمزهای یکبار مصرف ثبت نام کاربران',
            },
        ),
    ]
