# Generated by Django 5.1.7 on 2025-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregisterotp',
            name='username',
        ),
        migrations.AlterField(
            model_name='userregisterotp',
            name='user_type',
            field=models.CharField(max_length=2),
        ),
    ]
