# Generated by Django 5.1.7 on 2025-03-22 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_onetimepassword_phone_userregisterotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregisterotp',
            name='user_type',
            field=models.CharField(default='JS', max_length=2),
        ),
        migrations.AlterField(
            model_name='userregisterotp',
            name='otp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_otps', to='Authentication.onetimepassword', verbose_name='ارجاع رمز یکبار مصرف'),
        ),
    ]
