# Generated by Django 5.1.7 on 2025-05-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_userloginotp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregisterotp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userregisterotp',
            name='password_conf',
        ),
    ]
