# Generated by Django 5.1.7 on 2025-05-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Industry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='industrycategory',
            name='slug',
        ),
    ]
