# Generated by Django 5.1.7 on 2025-05-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industry', '0002_remove_industry_category_remove_industry_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='Industry.industrycategory', verbose_name='دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
