# Generated by Django 5.1.7 on 2025-04-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0003_alter_company_industry'),
        ('Industry', '0002_industry_icon_industrycategory_icon_skill'),
        ('Locations', '0002_city_slug_province_slug'),
        ('Profiles', '0005_remove_experience_job_seeker_and_more'),
        ('Resumes', '0001_initial'),
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('advertise_code', models.CharField(db_index=True, help_text='بعد از ثبت مقداردهی می\u200cشود', max_length=220, unique=True, verbose_name='کد آگهی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات بیشتر')),
                ('status', models.CharField(choices=[('Pending', 'در حال بررسی'), ('Approved', 'تایید شده'), ('Rejected', 'رد شده')], default='Pending', max_length=20, verbose_name='وضعیت آگهی')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن'), ('Not Specified', 'مهم نیست')], max_length=20, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('Completed', 'پایان خدمت'), ('Permanent Exemption', 'معافیت دائم'), ('Educational Exemption', 'معافیت تحصیلی'), ('Not Specified', 'مهم نیست')], max_length=30, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('Below Diploma', 'زیر دیپلم'), ('Diploma', 'دیپلم'), ('Associate', 'فوق دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('Doctorate', 'دکترا')], max_length=20, verbose_name='حداقل مدرک تحصیلی')),
                ('salary', models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=20, verbose_name='محدوده حقوق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advertisements_Industry', to='Industry.industry', verbose_name='صنعت')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advertisements_Location', to='Locations.city', verbose_name='موقعیت')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Advertisements_Subscription', to='Subscriptions.advertisementsubscription', verbose_name='اشتراک')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Full-Time', 'تمام وقت'), ('Part-Time', 'پاره وقت'), ('Remote', 'دورکاری'), ('Internship', 'کارآموزی')], max_length=20, verbose_name='نوع کار')),
                ('description_position', models.TextField(verbose_name='موقعیت شغلی')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_Advertisement', to='Advertisements.advertisement', verbose_name='آگهی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_Advertisement', to='Companies.company', verbose_name='شرکت')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employer_Advertisement', to='Profiles.employerprofile', verbose_name='کارفرما')),
            ],
            options={
                'verbose_name': 'آگهی کارفرما',
                'verbose_name_plural': 'آگهی\u200cهای کارفرما',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PE', 'در انتظار'), ('IR', 'در حال بررسی'), ('AC', 'پذیرفته شده'), ('RE', 'رد شده')], default='PE', max_length=20)),
                ('employer_notes', models.TextField(blank=True, null=True)),
                ('viewed_by_employer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to='Profiles.jobseekerprofile')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resumes.jobseekerresume')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to='Advertisements.jobadvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Full-Time', 'تمام وقت'), ('Part-Time', 'پاره وقت'), ('Remote', 'دورکاری'), ('Internship', 'کارآموزی')], max_length=20, verbose_name='نوع کار')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume_Advertisement', to='Advertisements.advertisement', verbose_name='آگهی')),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='Profiles.jobseekerprofile', verbose_name='پروفایل کارجو')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume', to='Resumes.jobseekerresume', verbose_name='رزومه')),
            ],
            options={
                'verbose_name': 'آگهی رزومه کارجو',
                'verbose_name_plural': 'آگهی\u200cهای رزومه کارجو',
            },
        ),
    ]
