# Generated by Django 5.1.7 on 2025-03-23 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0003_alter_company_industry'),
        ('Industry', '0001_initial'),
        ('Locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('advertise_code', models.CharField(db_index=True, help_text='بعد از ثبت مقداردهی می\u200cشود', max_length=220, unique=True, verbose_name='کد آگهی')),
                ('description_position', models.TextField(verbose_name='موقعیت شغلی')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='وضعیت آکهی')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن'), ('Not Specified', 'مهم نیست')], max_length=20, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('Completed', 'پایان خدمت'), ('Permanent Exemption', 'معافیت دائم'), ('Educational Exemption', 'معافیت تحصیلی'), ('Not Specified', 'مهم نیست')], max_length=30, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('Not Specified', 'مهم نیست'), ('Below Diploma', 'زیر دیپلم'), ('Diploma', 'دیپلم'), ('Associate', 'فوق دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('Doctorate', 'دکترا')], max_length=20, verbose_name='حداقل مدرک تحصیلی')),
                ('experience', models.CharField(choices=[('Does Not Matter', 'مهم نیست'), ('Less than Three', 'کمتر از 3 سال'), ('Three or More', '3 تا 6 سال'), ('Six or More', 'بیشتر از 6 سال')], max_length=50, verbose_name='حداقل سابقه کاری')),
                ('salary', models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=20, verbose_name='محدوده حقوق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='Companies.company')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='Industry.industry')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='Locations.city')),
            ],
            options={
                'verbose_name': 'آگهی کارفرما',
                'verbose_name_plural': 'آگهی کارفرمایان',
                'ordering': ['-created_at'],
            },
        ),
    ]
