# Generated by Django 5.1.7 on 2025-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvertisement',
            name='degree',
            field=models.CharField(blank=True, choices=[('BD', 'زیر دیپلم'), ('DI', 'دیپلم'), ('AS', 'فوق دیپلم'), ('BA', 'لیسانس'), ('MA', 'فوق لیسانس'), ('DO', 'دکترا')], max_length=2, null=True, verbose_name='حداقل مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن'), ('N', 'مهم نیست')], max_length=2, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'تمام وقت'), ('PT', 'پاره وقت'), ('RE', 'دورکاری'), ('IN', 'کارآموزی')], max_length=2, null=True, verbose_name='نوع کار'),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='salary',
            field=models.CharField(blank=True, choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], max_length=30, null=True, verbose_name='محدوده حقوق'),
        ),
        migrations.AlterField(
            model_name='jobadvertisement',
            name='soldier_status',
            field=models.CharField(blank=True, choices=[('CO', 'پایان خدمت'), ('EE', 'معافیت تحصیلی'), ('NS', 'مهم نیست')], max_length=2, null=True, verbose_name='وضعیت سربازی'),
        ),
        migrations.AlterField(
            model_name='resumeadvertisement',
            name='degree',
            field=models.CharField(blank=True, choices=[('BD', 'زیر دیپلم'), ('DI', 'دیپلم'), ('AS', 'فوق دیپلم'), ('BA', 'لیسانس'), ('MA', 'فوق لیسانس'), ('DO', 'دکترا')], max_length=2, null=True, verbose_name='حداقل مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='resumeadvertisement',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن'), ('N', 'مهم نیست')], max_length=2, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='resumeadvertisement',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FT', 'تمام وقت'), ('PT', 'پاره وقت'), ('RE', 'دورکاری'), ('IN', 'کارآموزی')], max_length=2, null=True, verbose_name='نوع کار'),
        ),
        migrations.AlterField(
            model_name='resumeadvertisement',
            name='salary',
            field=models.CharField(blank=True, choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=30, null=True, verbose_name='محدوده حقوق'),
        ),
        migrations.AlterField(
            model_name='resumeadvertisement',
            name='soldier_status',
            field=models.CharField(blank=True, choices=[('CO', 'پایان خدمت'), ('EE', 'معافیت تحصیلی'), ('NS', 'مهم نیست')], max_length=2, null=True, verbose_name='وضعیت سربازی'),
        ),
    ]
