# Generated by Django 5.1.7 on 2025-04-02 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Advertisement_Owner', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
            preserve_default=False,
        ),
    ]
