# Generated by Django 5.1.7 on 2025-06-02 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='slug',
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
