# Generated by Django 5.1.7 on 2025-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PE', 'در انتظار'), ('IR', 'در حال بررسی'), ('AC', 'پذیرفته شده'), ('RE', 'رد شده')], default='PE', max_length=20),
        ),
    ]
