# Generated by Django 5.1.7 on 2025-03-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0003_alter_application_status'),
        ('Industry', '0002_industry_icon_industrycategory_icon_skill'),
        ('Locations', '0002_city_slug_province_slug'),
        ('Profiles', '0005_remove_experience_job_seeker_and_more'),
        ('Resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerResumeAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='یک عنوان کوتاه برای آگهی', max_length=255, null=True, verbose_name='عنوان آگهی')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, help_text='توضیحات بیشتر درباره آگهی', null=True, verbose_name='شرح آگهی')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='وضعیت آکهی')),
                ('gender', models.CharField(choices=[('Male', 'مرد'), ('Female', 'زن')], max_length=20, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('Completed', 'پایان خدمت'), ('Permanent Exemption', 'معافیت دائم'), ('Educational Exemption', 'معافیت تحصیلی'), ('Not Completed', 'نااتمام')], max_length=30, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('Below Diploma', 'زیر دیپلم'), ('Diploma', 'دیپلم'), ('Associate', 'فوق دیپلم'), ('Bachelor', 'لیسانس'), ('Master', 'فوق لیسانس'), ('Doctorate', 'دکترا')], max_length=20, verbose_name='حداقل مدرک تحصیلی')),
                ('experience', models.CharField(choices=[('No EXPERIENCE', 'بدون سابقه کار'), ('Less than Three', 'کمتر از 3 سال'), ('Three or More', '3 تا 6 سال'), ('Six or More', 'بیشتر از 6 سال')], max_length=50, verbose_name='حداقل سابقه کاری')),
                ('salary', models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=20, verbose_name='محدوده حقوق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume_Advertisements', to='Industry.industry')),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobSeeker_Profile_Advertisements', to='Profiles.jobseekerprofile', verbose_name='پروفایل کار جو')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume_Advertisements', to='Locations.city')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume_Advertisements', to='Resumes.jobseekerresume', verbose_name='رزومه')),
            ],
        ),
    ]
