# Generated by Django 5.1.7 on 2025-03-20 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً Python, Java, طراحی گرافیک', max_length=100, unique=True, verbose_name='نام مهارت')),
                ('description', models.TextField(blank=True, help_text='شرح مختصر مهارت (اختیاری)', verbose_name='توضیحات مهارت')),
                ('icon', models.ImageField(blank=True, help_text='تصویر یا آیکون مرتبط با این مهارت (اختیاری)', null=True, upload_to='skill_icons/', verbose_name='آیکون مهارت')),
                ('website', models.URLField(blank=True, help_text='وبسایت مرتبط با مهارت (اختیاری)', verbose_name='وبسایت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="نام دسته\u200cبندی مهارت (مثلاً 'برنامه نویسی' یا 'طراحی')", max_length=50, unique=True, verbose_name='نام دسته')),
                ('slug', models.SlugField(help_text='اسلاگ برای دسته\u200cبندی که معمولاً از نام تولید می\u200cشود', unique=True, verbose_name='اسلاگ دسته')),
                ('icon', models.ImageField(blank=True, help_text='تصویر یا آیکون مرتبط با دسته\u200cبندی (اختیاری)', null=True, upload_to='skill_category_icons/', verbose_name='آیکون دسته')),
            ],
            options={
                'verbose_name': 'دسته مهارت',
                'verbose_name_plural': 'دسته\u200cهای مهارت',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='عنوان شغلی کوتاه (الزامی)', max_length=255, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, help_text='توضیح مختصر درباره خودتان', verbose_name='بیوگرافی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='jobseekers/profile_pics/', verbose_name='تصویر پروفایل')),
                ('location', models.CharField(help_text='شهر یا منطقه محل سکونت (الزامی)', max_length=255, verbose_name='مکان')),
                ('industry', models.CharField(blank=True, help_text='حوزه فعالیت شغلی', max_length=255, verbose_name='صنعت')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('linkedin_profile', models.URLField(blank=True, verbose_name='لینکدین')),
                ('resume', models.FileField(help_text='بارگذاری فایل رزومه (CV)', upload_to='jobseekers/resumes/', verbose_name='رزومه')),
                ('job_type_preference', models.CharField(blank=True, help_text='مثلاً تمام\u200cوقت یا پاره\u200cوقت', max_length=50, verbose_name='نوع شغل مورد نظر')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حقوق مورد انتظار')),
                ('id_card', models.FileField(help_text='بارگذاری تصویر/اسکن کارت ملی (الزامی)', upload_to='jobseekers/id_cards/', verbose_name='کارت ملی')),
                ('id_card_status', models.CharField(choices=[('P', 'در انتظار تایید'), ('V', 'تایید شده'), ('R', 'رد شده')], default='P', help_text='وضعیت بررسی کارت ملی', max_length=1, verbose_name='وضعیت کارت ملی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('skills', models.ManyToManyField(blank=True, help_text='انتخاب مهارت\u200cهای مرتبط از بین مهارت\u200cهای تعریف شده', to='Profiles.skill', verbose_name='مهارت\u200cها')),
            ],
            options={
                'verbose_name': 'پروفایل جوینده کار',
                'verbose_name_plural': 'پروفایل\u200cهای جویندگان کار',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان شغلی یا نقش در این تجربه', max_length=255, verbose_name='عنوان شغلی')),
                ('company', models.CharField(max_length=255, verbose_name='شرکت')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='مکان')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Profiles.jobseekerprofile', verbose_name='جوینده کار')),
            ],
            options={
                'verbose_name': 'تجربه کاری',
                'verbose_name_plural': 'تجربیات کاری',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255, verbose_name='دانشگاه/مدرسه')),
                ('degree', models.CharField(max_length=255, verbose_name='مدرک تحصیلی')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='Profiles.jobseekerprofile', verbose_name='جوینده کار')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'تحصیلات',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, help_text='انتخاب دسته\u200cبندی مهارت (اختیاری)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profiles.skillcategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
