# Generated by Django 5.1.7 on 2025-03-20 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='نام کامل شرکت (الزامی)', max_length=255, verbose_name='نام شرکت')),
                ('company_logo', models.ImageField(blank=True, help_text='لوگوی شرکت (اختیاری)', null=True, upload_to='employers/logos/', verbose_name='لوگوی شرکت')),
                ('website', models.URLField(blank=True, help_text='آدرس وبسایت شرکت (اختیاری)', verbose_name='وبسایت شرکت')),
                ('industry', models.CharField(blank=True, help_text='حوزه فعالیت شرکت (اختیاری)', max_length=255, verbose_name='صنعت')),
                ('company_size', models.CharField(blank=True, help_text='اندازه شرکت (مثلاً کوچک، متوسط، بزرگ) (اختیاری)', max_length=50, verbose_name='اندازه شرکت')),
                ('description', models.TextField(blank=True, help_text='شرح مختصری از شرکت و خدمات آن (اختیاری)', verbose_name='توضیحات شرکت')),
                ('location', models.CharField(help_text='شهر یا منطقه محل شرکت (الزامی)', max_length=255, verbose_name='مکان شرکت')),
                ('contact_email', models.EmailField(blank=True, help_text='ایمیل جهت تماس با شرکت (اختیاری)', max_length=254, verbose_name='ایمیل تماس شرکت')),
                ('contact_phone', models.CharField(blank=True, help_text='شماره تماس جهت ارتباط با شرکت (اختیاری)', max_length=20, verbose_name='شماره تماس شرکت')),
                ('established_date', models.DateField(blank=True, help_text='تاریخ تأسیس شرکت (اختیاری)', null=True, verbose_name='تاریخ تأسیس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کارفرما',
                'verbose_name_plural': 'پروفایل\u200cهای کارفرمایان',
            },
        ),
    ]
