# Generated by Django 5.1.7 on 2025-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_adminprofile_supportprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(default='M', max_length=5, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='kids_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فرزند'),
        ),
    ]
