# Generated by Django 5.1.7 on 2025-03-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_alter_employerprofile_industry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
