# Generated by Django 5.1.7 on 2025-03-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_delete_skill_delete_skillcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='kids_count',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='kids_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فرزند'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
