# Generated by Django 5.1.7 on 2025-04-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_remove_experience_job_seeker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='id_card_info',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='id_card_info',
        ),
        migrations.DeleteModel(
            name='IdCardInformation',
        ),
    ]
