# Generated by Django 5.1.7 on 2025-04-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Industry', '0002_industry_icon_industrycategory_icon_skill'),
        ('Locations', '0002_city_slug_province_slug'),
        ('Profiles', '0006_remove_jobseekerprofile_id_card_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='job_type_preference',
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Industry.industry', verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.city', verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Industry.industry', verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Locations.city', verbose_name='شهر'),
        ),
    ]
