# Generated by Django 5.1.7 on 2025-05-07 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_userloginotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginotp',
            name='otp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to='Authentication.onetimepassword', verbose_name='کد یکبار مصرف'),
        ),
    ]
