# Generated by Django 5.1.7 on 2025-06-02 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Companies', '0002_initial'),
        ('Industry', '0003_industry_category'),
        ('Locations', '0001_initial'),
        ('Resumes', '0001_initial'),
        ('Subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات بیشتر')),
                ('status', models.CharField(choices=[('P', 'در حال بررسی'), ('A', 'تایید شده'), ('R', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت آگهی')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('N', 'مهم نیست')], max_length=2, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('CO', 'پایان خدمت'), ('EE', 'معافیت تحصیلی'), ('NS', 'مهم نیست')], max_length=2, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('BD', 'زیر دیپلم'), ('DI', 'دیپلم'), ('AS', 'فوق دیپلم'), ('BA', 'لیسانس'), ('MA', 'فوق لیسانس'), ('DO', 'دکترا')], max_length=2, verbose_name='حداقل مدرک تحصیلی')),
                ('salary', models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=30, verbose_name='محدوده حقوق')),
                ('job_type', models.CharField(choices=[('FT', 'تمام وقت'), ('PT', 'پاره وقت'), ('RE', 'دورکاری'), ('IN', 'کارآموزی')], max_length=2, verbose_name='نوع کار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_advertisements', to='Companies.company', verbose_name='شرکت')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_advertisements', to=settings.AUTH_USER_MODEL, verbose_name='کارفرما')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisements_industry', to='Industry.industry', verbose_name='صنعت')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisements_location', to='Locations.city', verbose_name='موقعیت')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisement', to='Subscriptions.advertisementsubscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'آگهی کارفرما',
                'verbose_name_plural': 'آگهی\u200cهای کارفرما',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PE', 'در انتظار'), ('IR', 'در حال بررسی'), ('AC', 'پذیرفته شده'), ('RE', 'رد شده')], default='PE', max_length=2)),
                ('employer_notes', models.TextField(blank=True, null=True)),
                ('viewed_by_employer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resumes.jobseekerresume')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to='Advertisements.jobadvertisement')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAdvertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات بیشتر')),
                ('status', models.CharField(choices=[('P', 'در حال بررسی'), ('A', 'تایید شده'), ('R', 'رد شده')], default='P', max_length=2, verbose_name='وضعیت آگهی')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('N', 'مهم نیست')], max_length=2, verbose_name='جنسیت')),
                ('soldier_status', models.CharField(choices=[('CO', 'پایان خدمت'), ('EE', 'معافیت تحصیلی'), ('NS', 'مهم نیست')], max_length=2, verbose_name='وضعیت سربازی')),
                ('degree', models.CharField(choices=[('BD', 'زیر دیپلم'), ('DI', 'دیپلم'), ('AS', 'فوق دیپلم'), ('BA', 'لیسانس'), ('MA', 'فوق لیسانس'), ('DO', 'دکترا')], max_length=2, verbose_name='حداقل مدرک تحصیلی')),
                ('salary', models.CharField(choices=[('5 to 10', '5 تا 10 میلیون تومان'), ('10 to 15', '10 تا 15 میلیون تومان'), ('15 to 20', '15 تا 20 میلیون تومان'), ('20 to 30', '20 تا 30 میلیون تومان'), ('30 to 50', '30 تا 50 میلیون تومان'), ('More than 50', 'بیش از 50 میلیون تومان'), ('Negotiable', 'توافقی')], default='Negotiable', max_length=30, verbose_name='محدوده حقوق')),
                ('job_type', models.CharField(choices=[('FT', 'تمام وقت'), ('PT', 'پاره وقت'), ('RE', 'دورکاری'), ('IN', 'کارآموزی')], max_length=2, verbose_name='نوع کار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements_industry', to='Industry.industry', verbose_name='صنعت')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL, verbose_name='پروفایل کارجو')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements_location', to='Locations.city', verbose_name='موقعیت')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resume', to='Resumes.jobseekerresume', verbose_name='رزومه')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements_subscription', to='Subscriptions.advertisementsubscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'آگهی رزومه کارجو',
                'verbose_name_plural': 'آگهی\u200cهای رزومه کارجو',
            },
        ),
    ]
