# Generated by Django 5.1.7 on 2025-06-02 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0002_alter_jobadvertisement_degree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeadvertisement',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisements', to=settings.AUTH_USER_MODEL, verbose_name='پروفایل کارجو'),
        ),
    ]
