# Generated by Django 5.1.7 on 2025-06-03 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0003_alter_resumeadvertisement_job_seeker'),
        ('Subscriptions', '0002_alter_advertisementsubscription_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvertisement',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='resumeadvertisement',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='application',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Advertisements.jobadvertisement'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ad_type', models.CharField(choices=[('J', 'شغل'), ('R', 'رزومه')], max_length=1, verbose_name='نوع آگهی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='Subscriptions.advertisementsubscription', verbose_name='اشتراک')),
            ],
        ),
        migrations.AddField(
            model_name='jobadvertisement',
            name='advertisement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_advertisement', to='Advertisements.advertisement', verbose_name='آگهی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeadvertisement',
            name='advertisement',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume_advertisement', to='Advertisements.advertisement', verbose_name='آگهی'),
            preserve_default=False,
        ),
    ]
