# Generated by Django 5.1.7 on 2025-04-03 20:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advertisements', '0002_advertisement_owner'),
        ('Subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('total_price', models.IntegerField(verbose_name='قیمت نهایی')),
                ('order_id', models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertisements.advertisement', verbose_name='آگهی')),
                ('advertisement_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subscriptions.advertisementsubscription', verbose_name='اشتراک آکهی ها')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subscriptions.subscriptionplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'سفارش آگهی',
                'verbose_name_plural': 'سفارشات آگهی ها',
            },
        ),
    ]
