# Generated by Django 5.1.7 on 2025-04-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='durations',
            field=models.IntegerField(default=1, verbose_name='مدت زمان اشتراک'),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
