# Generated by Django 5.1.7 on 2025-04-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='شماره ملی')),
                ('id_card', models.FileField(blank=True, help_text='بارگذاری تصویر/اسکن کارت ملی', null=True, upload_to='jobseekers/id_cards/', verbose_name='کارت ملی')),
                ('id_card_status', models.CharField(choices=[('P', 'در انتظار تایید'), ('V', 'تایید شده'), ('R', 'رد شده')], default='P', help_text='وضعیت بررسی کارت ملی', max_length=1, verbose_name='وضعیت کارت ملی')),
            ],
            options={
                'verbose_name': 'اطلاعات کارت ملی',
                'verbose_name_plural': 'اطلاعات کارت ملی',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tfa_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth_status',
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_card_info', to='Users.idcardinformation', verbose_name='اطلاعات کارت ملی'),
            preserve_default=False,
        ),
    ]
