# Generated by Django 5.1.7 on 2025-04-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_idcardinformation_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcardinformation',
            name='id_card',
            field=models.FileField(blank=True, help_text='بارگذاری تصویر/اسکن کارت ملی', null=True, upload_to='Users/id_cards/', verbose_name='کارت ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_card_info', to='Users.idcardinformation', verbose_name='اطلاعات کارت ملی'),
        ),
    ]
