# Generated by Django 5.2.1 on 2025-06-03 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0004_remove_jobadvertisement_subscription_and_more'),
        ('Orders', '0001_initial'),
        ('Subscriptions', '0002_alter_advertisementsubscription_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='advertisement_subscription',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='ad_type',
            field=models.CharField(choices=[('J', 'شغل'), ('R', 'رزومه')], default=1, max_length=1, verbose_name='نوع آگهی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_orders', to='Advertisements.advertisement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to='Subscriptions.advertisementsubscription', verbose_name='اشتراک آگهی ها'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription_orders', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_orders', to='Subscriptions.subscriptionplan', verbose_name='پلن'),
        ),
    ]
